# Generated by Django 5.2 on 2025-06-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_customuser_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade_level',
            field=models.CharField(choices=[('kindergarten', 'Kindergarten'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6')], max_length=20),
        ),
    ]
