# Generated by Django 5.2 on 2025-06-13 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment_type',
            field=models.CharField(choices=[('Baseline', 'Baseline'), ('Terminal', 'Terminal')], default='Baseline', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_weighing',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(default='2025–2026', max_length=9),
        ),
    ]
