# Generated by Django 5.2 on 2025-06-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_assessment_type_student_date_of_weighing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assessment_type',
            field=models.CharField(choices=[('Baseline', 'Baseline'), ('Terminal', 'Terminal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_weighing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_year',
            field=models.CharField(max_length=9),
        ),
    ]
