# Generated by Django 5.2 on 2025-06-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
